# nelmio_api_doc:
#     documentation:
#         info:
#             title: My App
#             description: This is an awesome app!
#             version: 1.0.0
#     areas: # to filter documented areas
#         path_patterns:
#             - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

nelmio_api_doc:
    documentation:
        info:
            title: Bilemo
            description: Projet 7 de ma formation de Développeuse d'applications PHP/Symfony avec Openclassrooms
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - Token
                    operationId: postCredentialsItem
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: adminBilemo
                        password:
                            type: string
                            default: mdpass
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        # host_patterns: # document only routes with a host of the form api.*
        #     - ^api\.
